In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
import os

In [6]:
# Load the news datasets
news_df = pd.read_csv('cleaned_dataset/combined_news.csv')

In [7]:
news_df.head()

,title,text,subject,date,year,label,cleaned_title,cleaned_text
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,2017.0,False,donald trump sends out embarrassing new year’s...,donald trump wish american happy new year leav...
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,2017.0,False,drunk bragging trump staffer started russian c...,house intelligence committee chairman devin nu...
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,2017.0,False,sheriff david clarke becomes an internet joke ...,friday revealed former milwaukee sheriff david...
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,2017.0,False,trump is so obsessed he even has obama’s name ...,christmas day donald trump announced would bac...
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,2017.0,False,pope francis just called out donald trump duri...,pope francis used annual christmas day message...

In [14]:
# Create space-flag columns for a given text column
# Usage: add_space_flags(news_df, 'title', 'title')
#        add_space_flags(news_df, 'text', 'text')
def add_space_flags(df, col_name: str, label: str | None = None):
    if col_name not in df.columns:
        raise KeyError(f"Column '{col_name}' not found in dataframe")
    s = df[col_name].astype('string')
    lbl = label or col_name
    df[f"{lbl}_has_leading_space"] = s.str.startswith(' ', na=False)
    df[f"{lbl}_has_trailing_space"] = s.str.endswith(' ', na=False)

# Example (will be called in next cell)

In [15]:
add_space_flags(news_df, 'title', 'title')
add_space_flags(news_df, 'text', 'text')

In [16]:
news_df.head()

,title,text,subject,date,year,label,cleaned_title,cleaned_text,title_has_leading_space,title_has_trailing_space,text_has_leading_space,text_has_trailing_space
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,2017.0,False,donald trump sends out embarrassing new year’s...,donald trump wish american happy new year leav...,True,False,False,False
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,2017.0,False,drunk bragging trump staffer started russian c...,house intelligence committee chairman devin nu...,True,False,False,False
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,2017.0,False,sheriff david clarke becomes an internet joke ...,friday revealed former milwaukee sheriff david...,True,False,False,False
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,2017.0,False,trump is so obsessed he even has obama’s name ...,christmas day donald trump announced would bac...,True,False,False,False
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,2017.0,False,pope francis just called out donald trump duri...,pope francis used annual christmas day message...,True,False,False,False

In [ ]:
s = news_df['text'].astype('string').fillna('')
news_df['number_of_characters'] = s.str.len()
news_df['number_of_words'] = s.apply(lambda x: len(word_tokenize(x)))
news_df['number_of_sentences'] = s.apply(lambda x: len(sent_tokenize(x)))
news_df['url_count'] = s.apply(lambda x: len(re.findall(r'https?://\S+', x)))

cs = news_df['cleaned_text'].astype('string').fillna('')
news_df['unique_words'] = cs.apply(lambda x: len(set(word_tokenize(x))))

In [31]:
news_df['url_count'] = s.apply(lambda x: len(re.findall(r'https?://\S+', x)))

cs = news_df['cleaned_text'].astype('string').fillna('')
news_df['unique_words'] = cs.apply(lambda x: len(set(word_tokenize(x))))

In [32]:
news_df.head()

,title,text,subject,date,year,label,cleaned_title,cleaned_text,title_has_leading_space,title_has_trailing_space,text_has_leading_space,text_has_trailing_space,number_of_characters,number_of_words,number_of_sentences,url_count,unique_words
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,2017.0,False,donald trump sends out embarrassing new year’s...,donald trump wish american happy new year leav...,True,False,False,False,2893,599,28,0,158
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,2017.0,False,drunk bragging trump staffer started russian c...,house intelligence committee chairman devin nu...,True,False,False,False,1898,331,11,0,130
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,2017.0,False,sheriff david clarke becomes an internet joke ...,friday revealed former milwaukee sheriff david...,True,False,False,False,3597,689,25,1,207
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,2017.0,False,trump is so obsessed he even has obama’s name ...,christmas day donald trump announced would bac...,True,False,False,False,2774,519,15,4,162
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,2017.0,False,pope francis just called out donald trump duri...,pope francis used annual christmas day message...,True,False,False,False,2346,458,19,0,154

In [33]:
news_df.to_csv('cleaned_dataset/featureengineered_news.csv', index=False)